SELECT TOWN FROM WORKERS WHERE TOWN LIKE '% %';

SELECT(EMPLOYED+UNEMPLOYED+INACTIVE) AS TOTAL FROM WORKERS;

SELECT TOWN,(EMPLOYED+UNEMPLOYED+INACTIVE) AS TOTAL FROM WORKERS
ORDER BY TOTAL DESC LIMIT 10;

SELECT TOWN,INACTIVE/(EMPLOYED+UNEMPLOYED+INACTIVE)*100 AS PERCENT FROM WORKERS WHERE (EMPLOYED+UNEMPLOYED+INACTIVE) >= 10000
ORDER BY PERCENT DESC 

SELECT SUM(EMPLOYED)/SUM(EMPLOYED+UNEMPLOYED+INACTIVE)*100 FROM WORKERS;


/*UPDATE WORKERS SET EMPLOYED=EMPLOYED+10000 WHERE TOWN='STARA ZAGORA';*/
SELECT TOWN,(EMPLOYED)/(EMPLOYED+UNEMPLOYED+INACTIVE)*100 AS PERCENT FROM WORKERS 
ORDER BY PERCENT DESC;
SELECT (EMPLOYED+UNEMPLOYED+INACTIVE)*0.08 FROM WORKERS WHERE TOWN='BURGAS';

