SELECT Town,(EMPLOYED + UNEMPLOYED + INACTIVE) AS Population, ROUND(EMPLOYED*100/(EMPLOYED + UNEMPLOYED + INACTIVE),2) AS PercentEMPLOYED
FROM workers
WHERE (EMPLOYED + UNEMPLOYED + INACTIVE) BETWEEN 20000 AND 50000
ORDER BY PercentEMPLOYED DESC;